server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server


#\u5E94\u7528\u540D
#spring.application.name=eureka-server
##tomcat\u76D1\u542C\u7AEF\u53E3
#server.port=8761
#
##eureka\u4E3B\u673A\u5730\u5740
#eureka.instance.hostname=localhost
##\u7981\u7528eureka\u5BA2\u6237\u7AEF\u7684\u6CE8\u518C\u884C\u4E3A
#eureka.client.register-with-eureka=false
##\u5982\u679C\u4E3Atrue\uFF0C\u542F\u52A8\u65F6\u62A5\u8B66.
#eureka.client.fetch-registry=false